'use client';
import { useState } from 'react';import { useRouter } from 'next/navigation';import { LockKeyhole } from 'lucide-react';
type Status='ACTIVE'|'INACTIVE';type Sku={id?:string;internalCode?:string;spec:string;barcode:string;cainiao:string;status:Status};type Listing={id?:string;channel:string;shop:string;productExternalId:string;status:Status};type Product={id:string;name:string;brand:string;category:string;note:string;cainiaoCode:string;status:Status;skus:Sku[];listings:Listing[]};const channels=['淘宝','闲鱼','小红书','其他'];
const Toggle=({status,onClick}:{status:Status;onClick:()=>void})=><button type="button" className={status==='ACTIVE'?'status-active':'status-inactive'} onClick={onClick}>{status==='ACTIVE'?'使用中 · 点击停用':'已停用 · 点击启用'}</button>;
export default function Editor({product:initial}:{product:Product}){
 const [p,setP]=useState(initial);const [error,setError]=useState('');const [saving,setSaving]=useState(false);const router=useRouter();
 async function save(){setSaving(true);setError('');const r=await fetch(`/api/products/${p.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:p.name,brand:p.brand||null,category:p.category||null,note:p.note||null,cainiaoCode:p.cainiaoCode||null,status:p.status,skus:p.skus.map(({id,spec,barcode,cainiao,status})=>({id,spec,barcode,cainiao,status})),listings:p.listings})});const d=await r.json();if(!r.ok){setError(d.error);setSaving(false)}else{router.push(`/products/${p.id}`);router.refresh()}}
 return <div className="page"><div className="detail-head"><div><span className="eyebrow">EDIT RECORD</span><h1>编辑商品资料</h1><p className="sub">可新增规格；已生成的编码只能停用，永不删除或回收。</p></div><div className="top-actions"><Toggle status={p.status} onClick={()=>setP({...p,status:p.status==='ACTIVE'?'INACTIVE':'ACTIVE'})}/><button className="primary save-top" onClick={save} disabled={saving}>{saving?'保存中…':'保存全部修改'}</button></div></div>{error&&<div className="warning">{error}</div>}
 <div className="grid2"><section className="card form-card"><h2>商品信息</h2><div className="field"><label>商品名称 *</label><input value={p.name} onChange={e=>setP({...p,name:e.target.value})}/></div><div className="grid2"><div className="field"><label>品牌</label><input value={p.brand} onChange={e=>setP({...p,brand:e.target.value})}/></div><div className="field"><label>分类</label><input value={p.category} onChange={e=>setP({...p,category:e.target.value})}/></div></div><div className="field"><label>备注</label><textarea value={p.note} onChange={e=>setP({...p,note:e.target.value})}/></div></section>
 <section className="card form-card"><div className="detail-head"><div><h2>平台商品关系</h2><p className="sub">已保存关系不删除，可单独停用。</p></div><button type="button" className="primary" onClick={()=>setP({...p,listings:[...p.listings,{channel:'淘宝',shop:'',productExternalId:'',status:'ACTIVE'}]})}>＋ 添加平台</button></div>{p.listings.map((l,i)=><div className="platform-row" key={l.id||`new-${i}`}><div className="field"><label>平台</label><select value={l.channel} onChange={e=>setP({...p,listings:p.listings.map((x,n)=>n===i?{...x,channel:e.target.value}:x)})}>{channels.map(c=><option key={c}>{c}</option>)}</select></div><div className="field"><label>店铺名称</label><input value={l.shop} onChange={e=>setP({...p,listings:p.listings.map((x,n)=>n===i?{...x,shop:e.target.value}:x)})}/></div><div className="field"><label>平台商品 ID</label><input value={l.productExternalId} onChange={e=>setP({...p,listings:p.listings.map((x,n)=>n===i?{...x,productExternalId:e.target.value}:x)})}/></div>{l.id?<Toggle status={l.status} onClick={()=>setP({...p,listings:p.listings.map((x,n)=>n===i?{...x,status:x.status==='ACTIVE'?'INACTIVE':'ACTIVE'}:x)})}/>:<button type="button" onClick={()=>setP({...p,listings:p.listings.filter((_,n)=>n!==i)})}>移除未保存项</button>}</div>)}</section></div>
 <section className="card form-card" style={{marginTop:18}}><h2>商品级菜鸟云仓编码</h2><p className="sub">适合单规格商品；多规格商品扫码后进入商品信息。</p><div className="field" style={{maxWidth:520}}><label>商品级菜鸟云仓编码</label><input value={p.cainiaoCode} onChange={e=>setP({...p,cainiaoCode:e.target.value})} placeholder="粘贴菜鸟云仓商品编码"/></div></section>
 <section className="card form-card" style={{marginTop:18}}><div className="detail-head"><div><h2>规格与编码</h2><p className="sub">新增规格保存后自动获得下一个 yyhxfz 编码。</p></div><button type="button" className="primary" onClick={()=>setP({...p,skus:[...p.skus,{spec:'',barcode:'',cainiao:'',status:'ACTIVE'}]})}>＋ 新增规格</button></div>{p.skus.map((s,i)=><div className={`edit-sku ${s.status==='INACTIVE'?'inactive-block':''}`} key={s.id||`new-${i}`}><div className="field"><label>规格名称 *</label><input required value={s.spec} onChange={e=>setP({...p,skus:p.skus.map((x,n)=>n===i?{...x,spec:e.target.value}:x)})}/></div><div className="field"><label>{s.id&&<LockKeyhole style={{width:13,verticalAlign:'middle'}}/>} 内部编码</label><input className="locked" value={s.internalCode||'保存后自动生成'} readOnly disabled/></div><div className="field"><label>厂家条码</label><input value={s.barcode} onChange={e=>setP({...p,skus:p.skus.map((x,n)=>n===i?{...x,barcode:e.target.value}:x)})}/></div><div className="field"><label>菜鸟货品编码</label><input value={s.cainiao} onChange={e=>setP({...p,skus:p.skus.map((x,n)=>n===i?{...x,cainiao:e.target.value}:x)})}/></div><div>{s.id?<Toggle status={s.status} onClick={()=>setP({...p,skus:p.skus.map((x,n)=>n===i?{...x,status:x.status==='ACTIVE'?'INACTIVE':'ACTIVE'}:x)})}/>:<button type="button" onClick={()=>setP({...p,skus:p.skus.filter((_,n)=>n!==i)})}>移除未保存项</button>}</div></div>)}</section></div>
}
